
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bokemysql?useUnicode=true&characterEncoding=utf-8&&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

 # devtools:
 #   restart:
 #    enabled: true
 #    additional-paths:
 #      - src/main/java
 #    exclude: WEB-INF/**

  redis:
    host: localhost
    password: root
    database: 0
    port: 6379
    timeout: 5000

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  messages:
    encoding: UTF-8

  aop:
    auto: true
    proxy-target-class: true

server:
  port: 8080

  tomcat:
    uri-encoding: UTF-8

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count

logging:
  level:
    com.Blog.mapper.TagMapper: debug

